'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { signInWithGithubPrivate } from '@/app/auth/actions'
import {
  Download,
  GitBranch,
  ArrowRight,
  CheckCircle2,
  Loader2,
  AlertCircle,
  FileText,
  FileCode2,
  Lock,
} from 'lucide-react'
import { cn } from '@/lib/utils'

type Tab = 'llms' | 'llms-full'
type PushState = 'idle' | 'loading' | 'success' | 'error' | 'insufficient_permissions'

interface Props {
  llmsTxt: string
  llmsFullTxt: string
  repoName: string
  defaultBranch: string
  onGoToDashboard: () => void
}

export default function GeoFilesPreview({
  llmsTxt: initialLlmsTxt,
  llmsFullTxt: initialLlmsFullTxt,
  repoName,
  defaultBranch,
  onGoToDashboard,
}: Props) {
  const [activeTab, setActiveTab] = useState<Tab>('llms')
  const [llmsTxt, setLlmsTxt] = useState(initialLlmsTxt)
  const [llmsFullTxt, setLlmsFullTxt] = useState(initialLlmsFullTxt)
  const [pushState, setPushState] = useState<PushState>('idle')
  const [pushResult, setPushResult] = useState<{
    targetDir?: string
    urls?: { llmsTxt?: string; llmsFullTxt?: string }
    error?: string
  } | null>(null)

  const activeContent = activeTab === 'llms' ? llmsTxt : llmsFullTxt
  const activeFilename = activeTab === 'llms' ? 'llms.txt' : 'llms-full.txt'

  // ── Download ─────────────────────────────────────────────────────────────

  function downloadFile(content: string, filename: string) {
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  // ── GitHub Push ───────────────────────────────────────────────────────────

  async function handlePushToGitHub() {
    setPushState('loading')
    setPushResult(null)
    try {
      const res = await fetch('/api/push-to-github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ repoName, defaultBranch, llmsTxt, llmsFullTxt }),
      })
      const data = await res.json()
      
      if (res.status === 403) {
        setPushState('insufficient_permissions')
        setPushResult({ error: 'GitHub requires "repo" (write) scope to commit files.' })
        return
      }

      if (res.ok && data.success) {
        setPushState('success')
        setPushResult({ targetDir: data.targetDir, urls: data.urls })
      } else {
        setPushState('error')
        setPushResult({ error: data.error || 'Push failed' })
      }
    } catch {
      setPushState('error')
      setPushResult({ error: 'Network error — please try again' })
    }
  }

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="space-y-1">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="h-5 w-5 text-emerald-500" />
          <h2 className="text-xl font-bold text-slate-900">GEO Files Generated</h2>
        </div>
        <p className="text-sm text-slate-500">
          Review and edit the files below, then push to your GitHub repo or download them manually.
        </p>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 bg-slate-100 rounded-xl w-fit">
        <button
          onClick={() => setActiveTab('llms')}
          className={cn(
            'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all',
            activeTab === 'llms'
              ? 'bg-white text-indigo-700 shadow-sm'
              : 'text-slate-500 hover:text-slate-700'
          )}
        >
          <FileText className="h-4 w-4" />
          llms.txt
        </button>
        <button
          onClick={() => setActiveTab('llms-full')}
          className={cn(
            'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all',
            activeTab === 'llms-full'
              ? 'bg-white text-indigo-700 shadow-sm'
              : 'text-slate-500 hover:text-slate-700'
          )}
        >
          <FileCode2 className="h-4 w-4" />
          llms-full.txt
        </button>
      </div>

      {/* Tab description */}
      <p className="text-xs text-slate-400 -mt-3">
        {activeTab === 'llms'
          ? 'AI agent navigation index — generated by scanning your GitHub repository structure.'
          : 'Full GEO context document — assembled from your onboarding answers. Edited directly here.'}
      </p>

      {/* Editor */}
      <div className="relative rounded-2xl overflow-hidden border border-slate-200 shadow-sm bg-slate-950">
        {/* Editor header bar */}
        <div className="flex items-center justify-between px-4 py-2.5 bg-slate-900 border-b border-slate-800">
          <span className="text-xs font-mono text-slate-400">{activeFilename}</span>
          <button
            onClick={() => downloadFile(activeContent, activeFilename)}
            className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            Download
          </button>
        </div>
        {/* Editable textarea */}
        <textarea
          value={activeContent}
          onChange={e =>
            activeTab === 'llms' ? setLlmsTxt(e.target.value) : setLlmsFullTxt(e.target.value)
          }
          spellCheck={false}
          className="w-full h-[420px] bg-transparent text-green-300 font-mono text-[13px] leading-relaxed p-5 resize-none border-none focus:outline-none focus:ring-0 custom-scrollbar"
        />
      </div>

      {/* Push result banner */}
      {pushState === 'success' && pushResult && (
        <div className="flex items-start gap-3 p-4 bg-emerald-50 border border-emerald-200 rounded-xl">
          <CheckCircle2 className="h-5 w-5 text-emerald-600 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="text-sm font-semibold text-emerald-800">
              Successfully pushed to <code className="font-mono">{repoName}</code>
              {pushResult.targetDir && pushResult.targetDir !== '(repo root)' && (
                <> → <code className="font-mono">{pushResult.targetDir}</code></>
              )}
            </p>
            <div className="flex gap-3 flex-wrap">
              {pushResult.urls?.llmsTxt && (
                <a
                  href={pushResult.urls.llmsTxt}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-emerald-700 underline underline-offset-2 hover:text-emerald-900"
                >
                  View llms.txt on GitHub ↗
                </a>
              )}
              {pushResult.urls?.llmsFullTxt && (
                <a
                  href={pushResult.urls.llmsFullTxt}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-emerald-700 underline underline-offset-2 hover:text-emerald-900"
                >
                  View llms-full.txt on GitHub ↗
                </a>
              )}
            </div>
          </div>
        </div>
      )}

      {(pushState === 'error' || pushState === 'insufficient_permissions') && pushResult?.error && (
        <div className={cn(
          "flex items-start gap-3 p-4 border rounded-xl",
          pushState === 'insufficient_permissions' ? "bg-amber-50 border-amber-200" : "bg-red-50 border-red-200"
        )}>
          {pushState === 'insufficient_permissions' ? (
            <Lock className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
          ) : (
            <AlertCircle className="h-5 w-5 text-red-500 shrink-0 mt-0.5" />
          )}
          <div className="space-y-1">
            <p className={cn(
              "text-sm font-semibold",
              pushState === 'insufficient_permissions' ? "text-amber-800" : "text-red-800"
            )}>
              {pushState === 'insufficient_permissions' ? 'Write Access Required' : 'Push failed'}
            </p>
            <p className={cn(
              "text-xs",
              pushState === 'insufficient_permissions' ? "text-amber-600" : "text-red-500"
            )}>
              {pushResult.error}
            </p>
          </div>
        </div>
      )}

      {/* Action buttons */}
      <div className="flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-slate-100">
        {pushState === 'insufficient_permissions' ? (
          <form action={signInWithGithubPrivate}>
            <Button
              type="submit"
              className="gap-2 bg-indigo-600 hover:bg-indigo-700 text-white min-w-[200px]"
            >
              <Lock className="h-4 w-4" />
              Authorize Write Access
            </Button>
          </form>
        ) : (
          <Button
            className="gap-2 bg-slate-900 hover:bg-slate-800 text-white min-w-[160px]"
            onClick={handlePushToGitHub}
            disabled={pushState === 'loading' || pushState === 'success'}
          >
            {pushState === 'loading' ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : pushState === 'success' ? (
              <CheckCircle2 className="h-4 w-4 text-emerald-400" />
            ) : (
              <GitBranch className="h-4 w-4" />
            )}
            {pushState === 'success' ? 'Pushed Successfully' : 'Push to GitHub'}
          </Button>
        )}

        <Button
          variant="outline"
          className="gap-2 border-slate-200 text-slate-600 hover:bg-slate-50"
          onClick={onGoToDashboard}
        >
          Go to Dashboard
          <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </div>
  )
}
